# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dodo_detector_ros/DetectedObjectArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import dodo_detector_ros.msg
import std_msgs.msg

class DetectedObjectArray(genpy.Message):
  _md5sum = "cfb00e28c707bcf2e4252c82ba9b0d6c"
  _type = "dodo_detector_ros/DetectedObjectArray"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
dodo_detector_ros/DetectedObject[] detected_objects
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: dodo_detector_ros/DetectedObject
std_msgs/String type
std_msgs/String tf_id
std_msgs/Int32 image_x
std_msgs/Int32 image_y
std_msgs/Int32 image_height
std_msgs/Int32 image_width

================================================================================
MSG: std_msgs/String
string data

================================================================================
MSG: std_msgs/Int32
int32 data"""
  __slots__ = ['header','detected_objects']
  _slot_types = ['std_msgs/Header','dodo_detector_ros/DetectedObject[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,detected_objects

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DetectedObjectArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.detected_objects is None:
        self.detected_objects = []
    else:
      self.header = std_msgs.msg.Header()
      self.detected_objects = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.detected_objects)
      buff.write(_struct_I.pack(length))
      for val1 in self.detected_objects:
        _v1 = val1.type
        _x = _v1.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v2 = val1.tf_id
        _x = _v2.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v3 = val1.image_x
        _x = _v3.data
        buff.write(_get_struct_i().pack(_x))
        _v4 = val1.image_y
        _x = _v4.data
        buff.write(_get_struct_i().pack(_x))
        _v5 = val1.image_height
        _x = _v5.data
        buff.write(_get_struct_i().pack(_x))
        _v6 = val1.image_width
        _x = _v6.data
        buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.detected_objects is None:
        self.detected_objects = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.detected_objects = []
      for i in range(0, length):
        val1 = dodo_detector_ros.msg.DetectedObject()
        _v7 = val1.type
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v7.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v7.data = str[start:end]
        _v8 = val1.tf_id
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v8.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v8.data = str[start:end]
        _v9 = val1.image_x
        start = end
        end += 4
        (_v9.data,) = _get_struct_i().unpack(str[start:end])
        _v10 = val1.image_y
        start = end
        end += 4
        (_v10.data,) = _get_struct_i().unpack(str[start:end])
        _v11 = val1.image_height
        start = end
        end += 4
        (_v11.data,) = _get_struct_i().unpack(str[start:end])
        _v12 = val1.image_width
        start = end
        end += 4
        (_v12.data,) = _get_struct_i().unpack(str[start:end])
        self.detected_objects.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.detected_objects)
      buff.write(_struct_I.pack(length))
      for val1 in self.detected_objects:
        _v13 = val1.type
        _x = _v13.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v14 = val1.tf_id
        _x = _v14.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v15 = val1.image_x
        _x = _v15.data
        buff.write(_get_struct_i().pack(_x))
        _v16 = val1.image_y
        _x = _v16.data
        buff.write(_get_struct_i().pack(_x))
        _v17 = val1.image_height
        _x = _v17.data
        buff.write(_get_struct_i().pack(_x))
        _v18 = val1.image_width
        _x = _v18.data
        buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.detected_objects is None:
        self.detected_objects = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.detected_objects = []
      for i in range(0, length):
        val1 = dodo_detector_ros.msg.DetectedObject()
        _v19 = val1.type
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v19.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v19.data = str[start:end]
        _v20 = val1.tf_id
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v20.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v20.data = str[start:end]
        _v21 = val1.image_x
        start = end
        end += 4
        (_v21.data,) = _get_struct_i().unpack(str[start:end])
        _v22 = val1.image_y
        start = end
        end += 4
        (_v22.data,) = _get_struct_i().unpack(str[start:end])
        _v23 = val1.image_height
        start = end
        end += 4
        (_v23.data,) = _get_struct_i().unpack(str[start:end])
        _v24 = val1.image_width
        start = end
        end += 4
        (_v24.data,) = _get_struct_i().unpack(str[start:end])
        self.detected_objects.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
