; Auto-generated. Do not edit!


(cl:in-package object_recognition_msgs-msg)


;//! \htmlinclude ObjectRecognitionFeedback.msg.html

(cl:defclass <ObjectRecognitionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ObjectRecognitionFeedback (<ObjectRecognitionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ObjectRecognitionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ObjectRecognitionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name object_recognition_msgs-msg:<ObjectRecognitionFeedback> is deprecated: use object_recognition_msgs-msg:ObjectRecognitionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ObjectRecognitionFeedback>) ostream)
  "Serializes a message object of type '<ObjectRecognitionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ObjectRecognitionFeedback>) istream)
  "Deserializes a message object of type '<ObjectRecognitionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ObjectRecognitionFeedback>)))
  "Returns string type for a message object of type '<ObjectRecognitionFeedback>"
  "object_recognition_msgs/ObjectRecognitionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ObjectRecognitionFeedback)))
  "Returns string type for a message object of type 'ObjectRecognitionFeedback"
  "object_recognition_msgs/ObjectRecognitionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ObjectRecognitionFeedback>)))
  "Returns md5sum for a message object of type '<ObjectRecognitionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ObjectRecognitionFeedback)))
  "Returns md5sum for a message object of type 'ObjectRecognitionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ObjectRecognitionFeedback>)))
  "Returns full string definition for message of type '<ObjectRecognitionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#no feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ObjectRecognitionFeedback)))
  "Returns full string definition for message of type 'ObjectRecognitionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#no feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ObjectRecognitionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ObjectRecognitionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ObjectRecognitionFeedback
))
