; Auto-generated. Do not edit!


(cl:in-package object_recognition_msgs-msg)


;//! \htmlinclude ObjectRecognitionGoal.msg.html

(cl:defclass <ObjectRecognitionGoal> (roslisp-msg-protocol:ros-message)
  ((use_roi
    :reader use_roi
    :initarg :use_roi
    :type cl:boolean
    :initform cl:nil)
   (filter_limits
    :reader filter_limits
    :initarg :filter_limits
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass ObjectRecognitionGoal (<ObjectRecognitionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ObjectRecognitionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ObjectRecognitionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name object_recognition_msgs-msg:<ObjectRecognitionGoal> is deprecated: use object_recognition_msgs-msg:ObjectRecognitionGoal instead.")))

(cl:ensure-generic-function 'use_roi-val :lambda-list '(m))
(cl:defmethod use_roi-val ((m <ObjectRecognitionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader object_recognition_msgs-msg:use_roi-val is deprecated.  Use object_recognition_msgs-msg:use_roi instead.")
  (use_roi m))

(cl:ensure-generic-function 'filter_limits-val :lambda-list '(m))
(cl:defmethod filter_limits-val ((m <ObjectRecognitionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader object_recognition_msgs-msg:filter_limits-val is deprecated.  Use object_recognition_msgs-msg:filter_limits instead.")
  (filter_limits m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ObjectRecognitionGoal>) ostream)
  "Serializes a message object of type '<ObjectRecognitionGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'use_roi) 1 0)) ostream)
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'filter_limits))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'filter_limits))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ObjectRecognitionGoal>) istream)
  "Deserializes a message object of type '<ObjectRecognitionGoal>"
    (cl:setf (cl:slot-value msg 'use_roi) (cl:not (cl:zerop (cl:read-byte istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'filter_limits) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'filter_limits)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ObjectRecognitionGoal>)))
  "Returns string type for a message object of type '<ObjectRecognitionGoal>"
  "object_recognition_msgs/ObjectRecognitionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ObjectRecognitionGoal)))
  "Returns string type for a message object of type 'ObjectRecognitionGoal"
  "object_recognition_msgs/ObjectRecognitionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ObjectRecognitionGoal>)))
  "Returns md5sum for a message object of type '<ObjectRecognitionGoal>"
  "49bea2f03a1bba0ad05926e01e3525fa")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ObjectRecognitionGoal)))
  "Returns md5sum for a message object of type 'ObjectRecognitionGoal"
  "49bea2f03a1bba0ad05926e01e3525fa")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ObjectRecognitionGoal>)))
  "Returns full string definition for message of type '<ObjectRecognitionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Optional ROI to use for the object detection~%bool use_roi~%float32[] filter_limits~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ObjectRecognitionGoal)))
  "Returns full string definition for message of type 'ObjectRecognitionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Optional ROI to use for the object detection~%bool use_roi~%float32[] filter_limits~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ObjectRecognitionGoal>))
  (cl:+ 0
     1
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'filter_limits) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ObjectRecognitionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ObjectRecognitionGoal
    (cl:cons ':use_roi (use_roi msg))
    (cl:cons ':filter_limits (filter_limits msg))
))
