(cl:defpackage object_recognition_msgs-srv
  (:use )
  (:export
   "GETOBJECTINFORMATION"
   "<GETOBJECTINFORMATION-REQUEST>"
   "GETOBJECTINFORMATION-REQUEST"
   "<GETOBJECTINFORMATION-RESPONSE>"
   "GETOBJECTINFORMATION-RESPONSE"
  ))

